
ro = np.load("npy/ro.npy")
pr = np.load("npy/pr.npy")
vx = np.load("npy/vx.npy")
vy = np.load("npy/vy.npy")
vz = np.load("npy/vz.npy")
er = np.load("npy/er.npy")
fx = np.load("npy/fx.npy")
fy = np.load("npy/fy.npy")
fz = np.load("npy/fz.npy")
x = np.load("npy/x.npy")
y = np.load("npy/y.npy")
z = np.load("npy/z.npy")
bx = np.load("npy/bx.npy")
by = np.load("npy/by.npy")
bz = np.load("npy/bz.npy")
